[package]
name = "autogguf"
version = "0.1.0"
description = "Convert HuggingFace models to GGUF automatically."
authors = ["Britt Lewis <brittlewis12@gmail.com>"]
license = "Unlicense OR MIT OR Apache-2.0"
homepage = "https://github.com/brittlewis12/autogguf-rs"
repository = "https://github.com/brittlewis12/autogguf-rs"
keywords = ["huggingface", "gguf", "llama.cpp", "llm", "transformers"]
categories = ["command-line-utilities"]
edition = "2021"

[dependencies]
clap = { version = "4.5.17", features = ["derive", "env", "wrap_help"] }
futures-util = "0.3.30"
reqwest = { version = "0.12.7", features = ["stream"] }
shellexpand = { version = "3.1.0", features = ["full"] }
tokio = { version = "1.40.0", features = ["full"] }
